apiVersion: v1
kind: Pod
metadata:
  name: restricted-noncompliant-pod
spec:
  hostPID: true
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
