apiVersion: v1
kind: Pod
metadata:
  name: restart-onfailure
spec:
  restartPolicy: OnFailure
  containers:
    - name: fail-container
      image: busybox
      command: ['sh', '-c', 'echo "Running..."; sleep 5; exit 1']